# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import content_ingestion_service_pb2 as content__ingestion__service__pb2


class ContentIngestionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WriteContentProfiles = channel.unary_unary(
                '/e8.ContentIngestion/WriteContentProfiles',
                request_serializer=content__ingestion__service__pb2.WriteContentProfilesRequest.SerializeToString,
                response_deserializer=content__ingestion__service__pb2.WriteContentProfilesResponse.FromString,
                )


class ContentIngestionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WriteContentProfiles(self, request, context):
        """It creates/updates a list metadata entries for the specified contents,
        keyed by the content IDs. It overwrites the profile if there is an existing
        entry.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContentIngestionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WriteContentProfiles': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteContentProfiles,
                    request_deserializer=content__ingestion__service__pb2.WriteContentProfilesRequest.FromString,
                    response_serializer=content__ingestion__service__pb2.WriteContentProfilesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'e8.ContentIngestion', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ContentIngestion(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WriteContentProfiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/e8.ContentIngestion/WriteContentProfiles',
            content__ingestion__service__pb2.WriteContentProfilesRequest.SerializeToString,
            content__ingestion__service__pb2.WriteContentProfilesResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
