# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: content_ingestion_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='content_ingestion_service.proto',
  package='e8',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1f\x63ontent_ingestion_service.proto\x12\x02\x65\x38\"\xaa\x02\n\x0e\x43ontentProfile\x12\x12\n\ncontent_id\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06genres\x18\x03 \x03(\t\x12;\n\rgenome_scores\x18\x04 \x03(\x0b\x32$.e8.ContentProfile.GenomeScoresEntry\x12$\n\x04tags\x18\x05 \x03(\x0b\x32\x16.e8.ContentProfile.Tag\x12\x0f\n\x07imdb_id\x18\x06 \x01(\x03\x12\x0f\n\x07tmdb_id\x18\x07 \x01(\x03\x1a+\n\x03Tag\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x16\n\x0etimestamp_secs\x18\x02 \x01(\x03\x1a\x33\n\x11GenomeScoresEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"K\n\x1bWriteContentProfilesRequest\x12,\n\x10\x63ontent_profiles\x18\x01 \x03(\x0b\x32\x12.e8.ContentProfile\"\x1e\n\x1cWriteContentProfilesResponse2m\n\x10\x43ontentIngestion\x12Y\n\x14WriteContentProfiles\x12\x1f.e8.WriteContentProfilesRequest\x1a .e8.WriteContentProfilesResponseb\x06proto3'
)




_CONTENTPROFILE_TAG = _descriptor.Descriptor(
  name='Tag',
  full_name='e8.ContentProfile.Tag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='e8.ContentProfile.Tag.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp_secs', full_name='e8.ContentProfile.Tag.timestamp_secs', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=285,
)

_CONTENTPROFILE_GENOMESCORESENTRY = _descriptor.Descriptor(
  name='GenomeScoresEntry',
  full_name='e8.ContentProfile.GenomeScoresEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='e8.ContentProfile.GenomeScoresEntry.key', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='e8.ContentProfile.GenomeScoresEntry.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=338,
)

_CONTENTPROFILE = _descriptor.Descriptor(
  name='ContentProfile',
  full_name='e8.ContentProfile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content_id', full_name='e8.ContentProfile.content_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='e8.ContentProfile.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='genres', full_name='e8.ContentProfile.genres', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='genome_scores', full_name='e8.ContentProfile.genome_scores', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tags', full_name='e8.ContentProfile.tags', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imdb_id', full_name='e8.ContentProfile.imdb_id', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tmdb_id', full_name='e8.ContentProfile.tmdb_id', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CONTENTPROFILE_TAG, _CONTENTPROFILE_GENOMESCORESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=338,
)


_WRITECONTENTPROFILESREQUEST = _descriptor.Descriptor(
  name='WriteContentProfilesRequest',
  full_name='e8.WriteContentProfilesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content_profiles', full_name='e8.WriteContentProfilesRequest.content_profiles', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=415,
)


_WRITECONTENTPROFILESRESPONSE = _descriptor.Descriptor(
  name='WriteContentProfilesResponse',
  full_name='e8.WriteContentProfilesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=417,
  serialized_end=447,
)

_CONTENTPROFILE_TAG.containing_type = _CONTENTPROFILE
_CONTENTPROFILE_GENOMESCORESENTRY.containing_type = _CONTENTPROFILE
_CONTENTPROFILE.fields_by_name['genome_scores'].message_type = _CONTENTPROFILE_GENOMESCORESENTRY
_CONTENTPROFILE.fields_by_name['tags'].message_type = _CONTENTPROFILE_TAG
_WRITECONTENTPROFILESREQUEST.fields_by_name['content_profiles'].message_type = _CONTENTPROFILE
DESCRIPTOR.message_types_by_name['ContentProfile'] = _CONTENTPROFILE
DESCRIPTOR.message_types_by_name['WriteContentProfilesRequest'] = _WRITECONTENTPROFILESREQUEST
DESCRIPTOR.message_types_by_name['WriteContentProfilesResponse'] = _WRITECONTENTPROFILESRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ContentProfile = _reflection.GeneratedProtocolMessageType('ContentProfile', (_message.Message,), {

  'Tag' : _reflection.GeneratedProtocolMessageType('Tag', (_message.Message,), {
    'DESCRIPTOR' : _CONTENTPROFILE_TAG,
    '__module__' : 'content_ingestion_service_pb2'
    # @@protoc_insertion_point(class_scope:e8.ContentProfile.Tag)
    })
  ,

  'GenomeScoresEntry' : _reflection.GeneratedProtocolMessageType('GenomeScoresEntry', (_message.Message,), {
    'DESCRIPTOR' : _CONTENTPROFILE_GENOMESCORESENTRY,
    '__module__' : 'content_ingestion_service_pb2'
    # @@protoc_insertion_point(class_scope:e8.ContentProfile.GenomeScoresEntry)
    })
  ,
  'DESCRIPTOR' : _CONTENTPROFILE,
  '__module__' : 'content_ingestion_service_pb2'
  # @@protoc_insertion_point(class_scope:e8.ContentProfile)
  })
_sym_db.RegisterMessage(ContentProfile)
_sym_db.RegisterMessage(ContentProfile.Tag)
_sym_db.RegisterMessage(ContentProfile.GenomeScoresEntry)

WriteContentProfilesRequest = _reflection.GeneratedProtocolMessageType('WriteContentProfilesRequest', (_message.Message,), {
  'DESCRIPTOR' : _WRITECONTENTPROFILESREQUEST,
  '__module__' : 'content_ingestion_service_pb2'
  # @@protoc_insertion_point(class_scope:e8.WriteContentProfilesRequest)
  })
_sym_db.RegisterMessage(WriteContentProfilesRequest)

WriteContentProfilesResponse = _reflection.GeneratedProtocolMessageType('WriteContentProfilesResponse', (_message.Message,), {
  'DESCRIPTOR' : _WRITECONTENTPROFILESRESPONSE,
  '__module__' : 'content_ingestion_service_pb2'
  # @@protoc_insertion_point(class_scope:e8.WriteContentProfilesResponse)
  })
_sym_db.RegisterMessage(WriteContentProfilesResponse)


_CONTENTPROFILE_GENOMESCORESENTRY._options = None

_CONTENTINGESTION = _descriptor.ServiceDescriptor(
  name='ContentIngestion',
  full_name='e8.ContentIngestion',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=449,
  serialized_end=558,
  methods=[
  _descriptor.MethodDescriptor(
    name='WriteContentProfiles',
    full_name='e8.ContentIngestion.WriteContentProfiles',
    index=0,
    containing_service=None,
    input_type=_WRITECONTENTPROFILESREQUEST,
    output_type=_WRITECONTENTPROFILESRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONTENTINGESTION)

DESCRIPTOR.services_by_name['ContentIngestion'] = _CONTENTINGESTION

# @@protoc_insertion_point(module_scope)
