# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kafka_message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='kafka_message.proto',
  package='e8',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13kafka_message.proto\x12\x02\x65\x38\"\x1c\n\tTmdbEntry\x12\x0f\n\x07tmdb_id\x18\x01 \x01(\x03\"\x1c\n\tImdbEntry\x12\x0f\n\x07imdb_id\x18\x01 \x01(\x03\x62\x06proto3'
)




_TMDBENTRY = _descriptor.Descriptor(
  name='TmdbEntry',
  full_name='e8.TmdbEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tmdb_id', full_name='e8.TmdbEntry.tmdb_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=55,
)


_IMDBENTRY = _descriptor.Descriptor(
  name='ImdbEntry',
  full_name='e8.ImdbEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='imdb_id', full_name='e8.ImdbEntry.imdb_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=85,
)

DESCRIPTOR.message_types_by_name['TmdbEntry'] = _TMDBENTRY
DESCRIPTOR.message_types_by_name['ImdbEntry'] = _IMDBENTRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TmdbEntry = _reflection.GeneratedProtocolMessageType('TmdbEntry', (_message.Message,), {
  'DESCRIPTOR' : _TMDBENTRY,
  '__module__' : 'kafka_message_pb2'
  # @@protoc_insertion_point(class_scope:e8.TmdbEntry)
  })
_sym_db.RegisterMessage(TmdbEntry)

ImdbEntry = _reflection.GeneratedProtocolMessageType('ImdbEntry', (_message.Message,), {
  'DESCRIPTOR' : _IMDBENTRY,
  '__module__' : 'kafka_message_pb2'
  # @@protoc_insertion_point(class_scope:e8.ImdbEntry)
  })
_sym_db.RegisterMessage(ImdbEntry)


# @@protoc_insertion_point(module_scope)
