# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import user_ingestion_service_pb2 as user__ingestion__service__pb2


class UserIngestionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WriteUserProfiles = channel.unary_unary(
                '/e8.UserIngestion/WriteUserProfiles',
                request_serializer=user__ingestion__service__pb2.WriteUserProfilesRequest.SerializeToString,
                response_deserializer=user__ingestion__service__pb2.WriteUserProfilesResponse.FromString,
                )


class UserIngestionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WriteUserProfiles(self, request, context):
        """It creates/updates a list of new user profiles, keyed by the user IDs. The
        call overwrites the profiles if the they have already been created in the
        system.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserIngestionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WriteUserProfiles': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteUserProfiles,
                    request_deserializer=user__ingestion__service__pb2.WriteUserProfilesRequest.FromString,
                    response_serializer=user__ingestion__service__pb2.WriteUserProfilesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'e8.UserIngestion', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserIngestion(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WriteUserProfiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/e8.UserIngestion/WriteUserProfiles',
            user__ingestion__service__pb2.WriteUserProfilesRequest.SerializeToString,
            user__ingestion__service__pb2.WriteUserProfilesResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
