# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_ingestion_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='user_ingestion_service.proto',
  package='e8',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1cuser_ingestion_service.proto\x12\x02\x65\x38\"\x1e\n\x0bUserProfile\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\"B\n\x18WriteUserProfilesRequest\x12&\n\ruser_profiles\x18\x01 \x03(\x0b\x32\x0f.e8.UserProfile\"\x1b\n\x19WriteUserProfilesResponse2a\n\rUserIngestion\x12P\n\x11WriteUserProfiles\x12\x1c.e8.WriteUserProfilesRequest\x1a\x1d.e8.WriteUserProfilesResponseb\x06proto3'
)




_USERPROFILE = _descriptor.Descriptor(
  name='UserProfile',
  full_name='e8.UserProfile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='e8.UserProfile.user_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=66,
)


_WRITEUSERPROFILESREQUEST = _descriptor.Descriptor(
  name='WriteUserProfilesRequest',
  full_name='e8.WriteUserProfilesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_profiles', full_name='e8.WriteUserProfilesRequest.user_profiles', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=134,
)


_WRITEUSERPROFILESRESPONSE = _descriptor.Descriptor(
  name='WriteUserProfilesResponse',
  full_name='e8.WriteUserProfilesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=163,
)

_WRITEUSERPROFILESREQUEST.fields_by_name['user_profiles'].message_type = _USERPROFILE
DESCRIPTOR.message_types_by_name['UserProfile'] = _USERPROFILE
DESCRIPTOR.message_types_by_name['WriteUserProfilesRequest'] = _WRITEUSERPROFILESREQUEST
DESCRIPTOR.message_types_by_name['WriteUserProfilesResponse'] = _WRITEUSERPROFILESRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserProfile = _reflection.GeneratedProtocolMessageType('UserProfile', (_message.Message,), {
  'DESCRIPTOR' : _USERPROFILE,
  '__module__' : 'user_ingestion_service_pb2'
  # @@protoc_insertion_point(class_scope:e8.UserProfile)
  })
_sym_db.RegisterMessage(UserProfile)

WriteUserProfilesRequest = _reflection.GeneratedProtocolMessageType('WriteUserProfilesRequest', (_message.Message,), {
  'DESCRIPTOR' : _WRITEUSERPROFILESREQUEST,
  '__module__' : 'user_ingestion_service_pb2'
  # @@protoc_insertion_point(class_scope:e8.WriteUserProfilesRequest)
  })
_sym_db.RegisterMessage(WriteUserProfilesRequest)

WriteUserProfilesResponse = _reflection.GeneratedProtocolMessageType('WriteUserProfilesResponse', (_message.Message,), {
  'DESCRIPTOR' : _WRITEUSERPROFILESRESPONSE,
  '__module__' : 'user_ingestion_service_pb2'
  # @@protoc_insertion_point(class_scope:e8.WriteUserProfilesResponse)
  })
_sym_db.RegisterMessage(WriteUserProfilesResponse)



_USERINGESTION = _descriptor.ServiceDescriptor(
  name='UserIngestion',
  full_name='e8.UserIngestion',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=165,
  serialized_end=262,
  methods=[
  _descriptor.MethodDescriptor(
    name='WriteUserProfiles',
    full_name='e8.UserIngestion.WriteUserProfiles',
    index=0,
    containing_service=None,
    input_type=_WRITEUSERPROFILESREQUEST,
    output_type=_WRITEUSERPROFILESRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERINGESTION)

DESCRIPTOR.services_by_name['UserIngestion'] = _USERINGESTION

# @@protoc_insertion_point(module_scope)
