# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import pointwise_ranking_service_pb2 as pointwise__ranking__service__pb2


class PointwiseRankingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComputePointwiseEstimate = channel.unary_unary(
                '/e8.PointwiseRanking/ComputePointwiseEstimate',
                request_serializer=pointwise__ranking__service__pb2.PointwiseEstimateRequest.SerializeToString,
                response_deserializer=pointwise__ranking__service__pb2.PointwiseEstimateResponse.FromString,
                )


class PointwiseRankingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ComputePointwiseEstimate(self, request, context):
        """Computes Pr(likes(Content[j]) | User[i], theta).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PointwiseRankingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComputePointwiseEstimate': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputePointwiseEstimate,
                    request_deserializer=pointwise__ranking__service__pb2.PointwiseEstimateRequest.FromString,
                    response_serializer=pointwise__ranking__service__pb2.PointwiseEstimateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'e8.PointwiseRanking', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PointwiseRanking(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ComputePointwiseEstimate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/e8.PointwiseRanking/ComputePointwiseEstimate',
            pointwise__ranking__service__pb2.PointwiseEstimateRequest.SerializeToString,
            pointwise__ranking__service__pb2.PointwiseEstimateResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
